[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_counter = "Arf2LET7mchncY1Z24eZz71sqoPaFAb1RMtXeUvuET61"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -r tsx -p ./tsconfig.json -t 1000000 tests/*.ts"